vtk_file: ../data/mesh.vtk
receiver_locations_file: ../data/receiver_locations.csv
magnetic_properties_file: ../data/adjoints/inputs/geomag_pipe_sus_0.npy
ambient_magnetic_field: [820.5,16241.7,53380.0]
solver_mode: adjoint

